# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Write release version (deprecated)
        id: version_check_deprecated
        run: echo ::set-output name=version_deprecated::${GITHUB_REF/refs\/tags\//}
      - name: Read release version (deprecated)
        run: echo "Version Check Deprecated 👉 ${{ steps.version_check_deprecated.outputs.version_deprecated }}"

      - name: Write release version
        id: version_check
        run: echo "version_new=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Read release version
        run: echo "Version Check 👉 ${{ steps.version_check.outputs.version_new }}"

  experiment-with-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder_name: test-official
            storage_base_url: NUMBERS_STORAGE_BASE_URL
            storage_trusted_client_key: NUMBERS_STORAGE_TRUSTED_CLIENT_KEY
            bubble_db_url: NUMBERS_BUBBLE_DB_URL
            network_action_url: NUMBERS_BUBBLE_NETWORK_ACTION_URL
          - folder_name: test-storage-backend
            storage_base_url: NUMBERS_STORAGE_QA_BASE_URL
            storage_trusted_client_key: NUMBERS_STORAGE_QA_TRUSTED_CLIENT_KEY
            bubble_db_url: NUMBERS_BUBBLE_DB_URL
            network_action_url: NUMBERS_BUBBLE_NETWORK_ACTION_URL
          - folder_name: test-bubble-iframe
            storage_base_url: NUMBERS_STORAGE_BASE_URL
            storage_trusted_client_key: NUMBERS_STORAGE_TRUSTED_CLIENT_KEY
            bubble_db_url: NUMBERS_BUBBLE_DB_QA_URL
            network_action_url: NUMBERS_BUBBLE_NETWORK_ACTION_URL
          - folder_name: test-network-actions
            storage_base_url: NUMBERS_STORAGE_BASE_URL
            storage_trusted_client_key: NUMBERS_STORAGE_TRUSTED_CLIENT_KEY
            bubble_db_url: NUMBERS_BUBBLE_DB_URL
            network_action_url: NUMBERS_BUBBLE_NETWORK_ACTION_QA_URL
    steps:
      - name: Check matrix variables are loaded properly
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets[matrix.storage_base_url] }}
          NUMBERS_STORAGE_TRUSTED_CLIENT_KEY: ${{ secrets[matrix.storage_trusted_client_key] }}
          NUMBERS_BUBBLE_DB_URL: ${{ secrets[matrix.bubble_db_url] }}
          BUBBLE_API_URL: ${{ secrets.BUBBLE_API_URL }}
          NUMBERS_BUBBLE_NETWORK_ACTION_URL: ${{ secrets[matrix.network_action_url] }}
          NUMBERS_PQINA_NPM_KEY: ${{ secrets.NUMBERS_PQINA_NPM_KEY }}
          UPLOAD_FOLDER_NAME: ${{ matrix.folder_name }} 
        run: |
          echo "NUMBERS_STORAGE_BASE_URL is ${{ env.NUMBERS_STORAGE_BASE_URL }}"
          echo "NUMBERS_STORAGE_TRUSTED_CLIENT_KEY is ${{ env.NUMBERS_STORAGE_TRUSTED_CLIENT_KEY }}"
          echo "NUMBERS_BUBBLE_DB_URL is ${{ env.NUMBERS_BUBBLE_DB_URL }}"
          echo "BUBBLE_API_URL is ${{ env.BUBBLE_API_URL }}"
          echo "NUMBERS_BUBBLE_NETWORK_ACTION_URL is ${{ env.NUMBERS_BUBBLE_NETWORK_ACTION_URL }}"
          echo "NUMBERS_PQINA_NPM_KEY is ${{ env.NUMBERS_PQINA_NPM_KEY }}"
          echo "UPLOAD_FOLDER_NAME is ${{ env.UPLOAD_FOLDER_NAME }}"
